# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    time.sleep(5)
    self.driver.quit()


  def test_test02(self):
    self.driver.get("https://testerhome.com/")
    self.driver.set_window_size(1536, 824)
    self.driver.find_element(By.LINK_TEXT, "社团").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "霍格沃兹测试学院").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".col-xs-12:nth-child(1) .team-name").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".topic-22359 .title > a").click()
  
